//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tarot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back___Copy {
            get {
                object obj = ResourceManager.GetObject("back___Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upright: innocence, new beginnings, free spirit, Reversed: recklessness, taken advantage of, inconsideration.
        ///Upright: willpower, desire, creation, manifestation, Reversed: trickery, illusions, out of touch.
        ///Upright: intuitive, unconscious, inner voice, Reversed: lack of center, lost inner voice, repressed feelings.
        ///Upright: motherhood, fertility, nature, Reversed: dependence, smothering, emptiness, nosiness.
        ///Upright: authority, structure, control, fatherhood, Reversed: tyranny, rigidity, coldness.
        ///Upr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string carddescription {
            get {
                return ResourceManager.GetString("carddescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The World
        ///Judgement
        ///The Sun
        ///The Moon
        ///The Star
        ///The Tower
        ///The Devil
        ///Temperance
        ///Death
        ///The Hanged Man
        ///Justice
        ///The Wheel Of Fortune
        ///The Hermit
        ///Strength
        ///The Chariot
        ///The Lovers
        ///The Hierophant
        ///The Emperor
        ///The Empress
        ///The High Priestess
        ///The Magician
        ///The Fool
        ///Ace Of Wands
        ///Two Of Wands
        ///Three Of Wands
        ///Four Of Wands
        ///Five Of Wands
        ///Six Of Wands
        ///Seven Of Wands
        ///Eight Of Wands
        ///Nine Of Wands
        ///Ten Of Wands
        ///Page of Wands
        ///Queen Of Wands
        ///King Of Wands
        ///Knight Of Wands
        ///Ace Of Cups
        ///Two Of Cups
        ///Th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cardnames {
            get {
                return ResourceManager.GetString("cardnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to theworld.png
        ///judgement.png
        ///thesun.png
        ///themoon.png
        ///thestar.png
        ///thetower.png
        ///thedevil.png
        ///temperance.png
        ///death.png
        ///thehangedman.png
        ///justice.png
        ///thewheeloffortune.png
        ///thehermit.png
        ///strength.png
        ///thechariot.png
        ///thelovers.png
        ///thehierophant.png
        ///theemperor.png
        ///theempress.png
        ///thehighpriestess.png
        ///themagician.png
        ///thefool.png
        ///aceofw.png
        ///twoofw.png
        ///threeofw.png
        ///fourofw.png
        ///fiveofw.png
        ///sixofw.png
        ///sevenofw.png
        ///eightofw.png
        ///nineofw.png
        ///tenofw.png
        ///pageofw.png
        ///queenofw.png
        ///kingofw.png
        ///knig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string imagenames {
            get {
                return ResourceManager.GetString("imagenames", resourceCulture);
            }
        }
    }
}
